print("Two vectors of different lengths:")
v1 =  c(1,3,5,7,9)
v2 =  c(0,2,4,6,8)
print(v1)
print(v2)
result = array(c(v1,v2),dim = c(3,3,2))
print("New array:")
print(result)
print("The second row of the second matrix of the array:")
print(result[2,,2])
print("The element in the 3rd row and 3rd column of the 1st matrix:")
print(result[3,3,1])
